server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: empirica_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: empirica
          __path__: /var/log/empirica/*.log

  - job_name: docker_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
    relabel_configs:
      - source_labels:
          - __docker_container_name
        target_label: container_name
      - source_labels:
          - __docker_container_id
        target_label: container_id

  - job_name: systemd_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: systemd
    relabel_configs:
      - source_labels:
          - __systemd_unit
        target_label: unit
